# Generated by Django 5.1.1 on 2024-10-31 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='lunch',
            new_name='lunches',
        ),
    ]
